#!/usr/bin/env bash
#
#     Yigid BALABAN, <fyb@fybx.dev>
#

echo "go crazy! go stupid!"
sudo cpupower frequency-set -g powersave
sudo echo power | tee /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference
bash "$HOME/scripts/utility/change_hyprland_mode.sh" save
sudo powertop --auto-tune
systemctl --user stop deskenv.timer
killall swww-daemon
